name: End-to-end tests
# push event
on:
  push:
    branches: [master]

# workflow triggered
jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome90-ff88

    # steps -> sequence of tasks
    steps:
      - name: Checkout code from Repository
        uses: actions/checkout@v2

      - name: Install a project with a clean slate
        run: |
          npm ci
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run gactions
        continue-on-error: true

      - name: Copy test execution videos
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          cp -r cypress/screenshots public/screenshots

      - name: Merge test results into one
        run: npm run mergereports
      - name: Generate HTML report
        run: npm run generatereport
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
